cards/urls.py
from django.urls import path, include

from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'cards'

urlpatterns = [
    path('',views.homePage,name='homePage'),

    path('all',views.allCards,name='allCards'),

    # every language has his own url
    path('python',views.pythonList,name='pythonList'),
    path('django',views.djangoList,name='djangoList'),
    path('jscript',views.jscriptList,name='jscriptList'),
    path('html',views.htmlList,name='htmlList'),
    path('css',views.cssList,name='cssList'),
    
    path('addCode',views.addNewCode,name='addCode'),
    
    path('your-add',views.userCard,name='userCards'),
    path('<str:slug>',views.singelCard,name='cardDetail'),
    path('edit-card/<str:slug>',views.editCard,name='editCard'),
    path('search-result/',views.search,name='search'),
]

codeCollection/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='account')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
    path('',include('cards.urls',namespace='home')),
    path('brows-code/',include('cards.urls',namespace='cardsShow')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include

from . import views
app_name = 'home'
urlpatterns = [
    path('',views.home,name='home'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'homeTemplate/home.html',{})

home/templates/homeTemplate/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fontAwesome/fontawesome-free-5.15.4-web/css/all.css' %}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="'https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Batang&family=STIX+Two+Text&display=swap" rel="stylesheet">

    <title>Collections Code</title>
</head>
<body>
    <header id="head">
        <nav id="topNav">
            <ul id="homeList">
                <li> <a href="{% url 'home:home' %}">Home</a> </li>
                <li> <a href="{% url 'cardsShow:allCards' %}">Browse Code</a> </li>
                <li> <a href="#">Add Code</a> </li>
            </ul>
            <ul id="login">
                <li> <a href="#"> <img src="https://via.placeholder.com/150" alt="img"> </a></li>
                <form action="">
                    <input id="loginClick" type="button" value="Login" >
                </form>
            </ul>
        </nav>
    </header>
    <section class="mainSection">
        <article id="leftSide">
            <nav id="leftNav">
                <ul>
                    <li><i class="fab fa-python"></i> <a href="#"> Python</a> </li>
                    <li>
                        <img src="{% static 'images/dj.png' %}" alt="dj" id="dj"> 
                        <a href="#">Django </a>
                    </li>
                    <li> <i class="fab fa-js-square"></i><a href="#"> JScript </a></li>
                    <li><i class="fab fa-html5"></i><a href="#"> HTML </a></li>
                    <li> <i class="fab fa-css3-alt"></i><a href="#"> CSS </a></li>
                </ul>
            </nav>
        </article>
        <article id="rightSide">
            <section id="subject">
                <h1>Search or Add CODE</h1>
            </section>
            <section id="mainLetter">
                <p>This page is about to make your work easy just search what you want 
                    in which program language you need 
                </p>
            </section>
            <section id="searchBar">
                <form method="get">
                    <label for="text1" id="labelName">Search Subject Code : </label>
                    <input id="text1" type="text" name="text1">
                    <input type="button" value="Search" id="searchBtn">
                    <i class="fas fa-search" id="searchIcon"></i>
                </form>
            </section>
            <!-- <section class="cards">
                <article class="card">
                    <div id="imgCard">
                        <img src="https://via.placeholder.com/120" alt="">
                    </div>
                    <div class="cardSubject">
                        <a href="#"> heigh line card </a>
                    </div>
                    <div class="cardDescription">
                        <p>What does LIM mean? We know 142 definitions for LIM 
                            abbreviation or acronym in 8 categories. Possible
                            LIM meaning as an acronym, abbreviation, shorthand 
                            or slang term vary from category to category. Please 
                            look for them carefully. Read more at 
                            http://acronymsandslang.com/meaning-of/chat-and-sub-cultures/LIM.html
                        </p>
                    </div>
                </article>
            </section> -->
        </article>
    <!-- {% block body %}

    
    {% endblock body %} -->
    </section>
    <footer>
        Do not give Up Some Day you will Be some One :)
    </footer>
</body>
</html>