accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    # path('log-out',views.logout_view,name='log-out'),
    path('signup',views.signUp,name='signup'),
    path('profile/',views.profileUser,name='profile'),
    path('profileEdit',views.profileEdit,name='profileEdit'),
]

codeCollection/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='account')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
    path('',include('cards.urls',namespace='home')),
    path('brows-code/',include('cards.urls',namespace='cardsShow')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include

from . import views
app_name = 'home'
urlpatterns = [
    path('',views.home,name='home'),
]

accounts/models.py
from django.db import models
# import the user from django is built in 
# the same user in admin 
from django.contrib.auth.models import User

# to create profile for the user
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

# create profile class
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='user_profile',default='/default/defaultImg.png')
    phone_number = models.CharField(max_length=25)

    def __str__(self):
        return str(self.user)


# create new user --> create new empty profile
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms

# to create a form to sign up a new user and django control it
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class SignUpForm(UserCreationForm):
    class Meta:
        # from User class in django
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']


class UserForm(forms.ModelForm):
    # image = forms.ImageField(widget=forms.FileInput,)
    class Meta:
        # from User class in django
        model = User
        fields = ['username','first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    # hide the image link from the form
    image = forms.ImageField(widget=forms.FileInput,)
    class Meta:
        # from Profile class
        model = Profile
        fields = ['image','phone_number']

accounts/views.py
from django.shortcuts import redirect, render
from .models import Profile
from .forms import UserForm,ProfileForm,SignUpForm
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def profileUser(request):
    # user is the fields in Profile models
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})

# this function let us edit the user information receive the data from User class
# and from Profile class we created 
def profileEdit(request):
    # user is the fields in Profile models
    profile = Profile.objects.get(user= request.user)
    if request.method == 'POST':
        userForm = UserForm(request.POST, instance=request.user)
        profileForm = ProfileForm(request.POST, request.FILES,instance=profile)
        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
            myProfile = profileForm.save(commit=False)
            myProfile.user = request.user
            myProfile.save()
            return redirect(reverse('account:profile'))
    else:
        userForm = UserForm(instance=request.user)
        profileForm = ProfileForm(instance=profile)
    return render(request,'accounts/profile_edit.html',{'userform':userForm,'profileForm':profileForm})


def signUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid() :
            form.save()
            
#after save update section to login and take username and pass to login
# form.cleaned_data it is allow to fetch data from the form we use it like dict 
# print form.cleaned_data to show the fields u want
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user1 = authenticate(username=username,password=password)
#after update and authenticate make login function in django
            login(request,user1)
            return redirect('account:profile')

    else:
        form = SignUpForm()
    return render(request,'registration/signup.html',{'form':form})

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load bootstrap5 %}


{% block body %}
    <article id="rightSide">
        <ul>
            <h3>Name: <span>{{profile}}</span></h3>
            <h3>Email: <span>{{profile.user.email}}</span></h3>
            <h3>Phone: <span> {{profile.phone_number}}</span></h3>
        </ul>
        <div class="p-5">
            <a class="boxed-btn3 w-100" href="{% url 'account:profileEdit' %}">Edit Profile</a>
        </div>
    </article>
{% endblock body %}  

accounts/templates/accounts/profile_edit.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block body %}


<article class="rightSection">
    <div class="profileEdit">
        <h4>Edit Profile</h4>
        <!-- without enctype='multipart/form-data' the image dose not upload -->
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {% bootstrap_form userform %}
            {% bootstrap_form profileForm %}
            <!-- center btn  -->
            <div class="col text-center">
                {% buttons %}
                <!-- width w-50 is 50% -->
                <button type="submit" class="btn btn-primary w-50">Save</button>
            {% endbuttons %}
            </div>
        </form>
    </article>
    </div>

{% endblock body %}  