cards/urls.py
from django.urls import path, include

from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'cards'

urlpatterns = [
    path('',views.homePage,name='homePage'),

    path('all',views.allCards,name='allCards'),

    # every language has his own url
    path('python',views.pythonList,name='pythonList'),
    path('django',views.djangoList,name='djangoList'),
    path('jscript',views.jscriptList,name='jscriptList'),
    path('html',views.htmlList,name='htmlList'),
    path('css',views.cssList,name='cssList'),
    
    path('addCode',views.addNewCode,name='addCode'),
    
    path('your-add',views.userCard,name='userCards'),
    path('<str:slug>',views.singelCard,name='cardDetail'),
    path('edit-card/<str:slug>',views.editCard,name='editCard'),
    path('search-result/',views.search,name='search'),
]

codeCollection/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='account')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
    path('',include('cards.urls',namespace='home')),
    path('brows-code/',include('cards.urls',namespace='cardsShow')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include

from . import views
app_name = 'home'
urlpatterns = [
    path('',views.home,name='home'),
]

cards/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=25)
    image = models.ImageField(upload_to='categoryPhoto/')
    def __str__(self):
        return self.name



class Cards(models.Model):
    owner = models.CharField(max_length=50)
    header = models.CharField(max_length=100)

    # drop box with options from category 
    category = models.ForeignKey(Category, on_delete=models.CASCADE) # on delete delete all data
    
    language_type = models.CharField(max_length=50)
    image = models.ImageField(upload_to='photo/')
    description = models.TextField(max_length=500)

    # code blog
    code_blog = models.TextField(max_length=5000)

    # date field to show when is the code wrote
    publish_at = models.DateField(auto_now_add=True)

    # slug used to rename the url in website like google/title.com
    slug = models.SlugField(blank=True, null=True)
    
    # function change the save button behavior in admin site override
    def save(self,*args, **kwargs):
        self.slug = slugify(self.header) #slugify convert the spaces in title to (-)
        super(Cards,self).save(*args, **kwargs)

    def __str__(self):
        return self.header


class AddNewCode(models.Model):
    code = models.ForeignKey(Cards, related_name='insert_code', on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE) # on delete delete all data
    upload_img = models.ImageField(upload_to='uploadImg/')
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return 

cards/views.py
from django.shortcuts import redirect, render
from . models import Cards
from django.core.paginator import Paginator
from .form import AddCode,EditCode
from django.urls import reverse
from .filters import CardFilter
from django.db.models.query_utils import Q


# Create your views here.

# will browse all the cards in data base
def allCards(request):
    all_cards = Cards.objects.all()

    paginator = Paginator(all_cards, 3) # Show 1 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'allCard':all_cards,
                'page_obj':page_obj,
                }

    return render(request,'allCards/cards.html',context)

# make filter to the user for his added cards and can edit
def userCard(request):
    cards = Cards.objects.all().filter(owner=request.user.username)
    print(cards)

    paginator = Paginator(cards, 3) # Show 1 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request,'allCards/userCards.html',{'cards':cards,'page_obj':page_obj})

# will open a single page for the card with the title of the card
def singelCard(request,slug):
    card = Cards.objects.get(slug=slug)
    image = card.image
    header = card.header
    description = card.description
    category = card.category 
    code = card.code_blog
    date = card.publish_at
    writer = card.owner
    categoryImage = category.image

    # use sluge to be argument to editCard path to link the same blog 
    sluge = card.slug

    
    # the class name is language-css (example) so we take the name from catgorey and pass in languageStyle
    # and render in html then the code colored in the blog cause we use prism.css 
    # show in the style code blog for which languages
    languageStyle = f'language-{category}'

    context = {
            'cardTitle':card,
            'cardImage':categoryImage,
            'header':header,
            'description':description,
            'lType':languageStyle,
            'code':code,
            'date':date,
            'writer':writer,
            'sluge':sluge,
            }

    return render(request,'allCards/cardDetail.html', context)


# will filter data base for the name of category number (muster function for all languages)
# languageListcategory : 1 - python, 2 - javaScript, 3 - html, 4 - css, 5 - django
def languageListcategory(name,category,request):
    language = Cards.objects.filter(category=category)
    # language will print all cards related to the category then used list 0 to access first item and bring image
    image = language[0].image

    paginator = Paginator(language, 3) # Show contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request,'allCards/cards.html',{f'{name}':language,'page_obj':page_obj,'Image':image})


# for python cards
def pythonList(request):
    return languageListcategory('python',1,request)

# for django
def djangoList(request):
    return languageListcategory('django',5,request)

#for java script
def jscriptList(request):
    return languageListcategory('java script',2,request)
    
# for html
def htmlList(request):
    return languageListcategory('html',3,request)

# for css
def cssList(request):
    return languageListcategory('Css',4,request)



# render the home page cause have another section it is not include in another pages
def homePage(request):
    return render(request,'allCards/home1.html',{})

# to search the cards that contain the words in input field search
def search(request):
    # request from the search field in home page or search bar from base
    if request.method == 'GET':
        # this will get the name of the input we named search in base.html and home.html and will look for this name
        query = request.GET.get('search')
        # filter the cards that header and description contin the text from the input
        result = Cards.objects.filter(Q(header__icontains=query) | Q(description__icontains=query))

    return render(request,'allCards/search_page.html',{'query':query,'result':result})

"""
    we can use user User class built in django and all attribute in the html files
    user.profile.image.url direct in html file will show us the image of the user hade been login

"""
########################################################################
# this how can we get the photo of user from profile class same for the other
# def img(request):
#     userImage = request.user.profile.image
#     # print( type(userImage) )
#     return render(request,'',{'userImage':userImage})
########################################################################

# for adding new cards in data base
def addNewCode(request):
    if request.method == 'POST':
        form = AddCode(request.POST, request.FILES)
        if form.is_valid():
            myForm = form.save(commit=False)
            myForm.owner = request.user

            myForm.language_type = myForm.category
            # cause image field is not exist and empty in form and category related the image, before we save we access the image from category image
            myForm.image = myForm.category.image

            myForm.save()
            return redirect(reverse('cardsShow:allCards'))
    else:
        form = AddCode()

    return render(request,'allCards/addCode.html',{'form':form})

# editing the description and the code block
def editCard(request,slug):
    edit = None
    card = Cards.objects.get(slug=slug)
    if request.method == 'POST':
        edit = EditCode(request.POST, instance=card)
        if edit.is_valid():
            editForm = edit.save(commit=False)
            editForm.user = request.user
            editForm.save()
            # pass the argument like this slug=slug to return to the same page after edit
            # because cardDetail need argument and is the slug 
            return redirect('cardsShow:cardDetail', slug=slug)
    else:
        edit = EditCode(instance=card)
    return render(request,'allCards/edit_card.html',{'form':edit})

cards/templates/allCards/addCode.html
{% extends 'base.html' %}
{% block title %}
    <title>Add Code</title>
{% endblock title %}

{% load bootstrap5 %}

{% block body %}
<article id="rightSide">
    <div class="leftItem">
        <form action="#" method="POST" class="form" enctype='multipart/form-data'>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary w-100" >Add Code</button>
            {% endbuttons %}
        </form>
        </div>
</article>

{% endblock body %}

cards/templates/allCards/cardDetail.html
{% extends "base.html" %}
{% block title %}
    <title>{{ cardTitle }}</title>
{% endblock title %}

{% block pageImg %}
<!-- do not forget .url for image in django -->
    <link rel="icon" href="{{ cardImage.url }}">
{% endblock pageImg %}

{% block body %}
<section class="cards">
    <div class="headerDetail">
        {{ header }}
        <div class="writer">
            {{writer}}
            {{date}}

            <!-- if the name of the publish blog is same of the user show edit link -->
            {% if writer == user.username %}
            <!-- pass sluge parameters to editCard  -->
            <p> <a href="{% url 'cardsShow:editCard' sluge  %}">Edit</a> </p>
            {% else %}
            <span></span>
            {% endif %}
        </div>
    </div>
    <div class="description">
        {{ description }}
    </div>
    <!-- do not make any space between cause will format the text in funny way -->
    <div class="code_blog">
        <pre><code class="{{ lType }}">{{ code }}</code></pre>
    </div>
</section>

{% endblock body %}

cards/templates/allCards/cards.html
{% extends 'base.html' %}

{% block title %}
    <title>Browse Code</title>
{% endblock title %}

{% block pageImg %}
<!-- do not forget .url for image in django -->
    <link rel="icon" href="{{ Image.url }}">
{% endblock pageImg %}

<!-- {% load bootstrap5 %} -->

{% block body %}
<article id="rightSide">
    <section class="cards">
        {% for card in page_obj.object_list %}
            <article class="card">
                    <div id="imgCard">
                        <img src="{{card.image.url}}" alt="">
                    </div>
                    <div class="codeWriter">
                        {{card.owner}}
                        <!-- {{user.first_name}} -->
                        {{card.publish_at}}
                    </div>
                    <div class="cardSubject">
                        <a href="{% url 'cardsShow:cardDetail' card.slug %}"> {{card.header}} </a>
                    </div>
                    <div class="cardDescription">
                        <p>
                            {{card.description}}
                        </p>
                    </div>
                    
            </article> 
        {% endfor %}
    </section>
    <!-- paginator setting -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            {% if page_obj.has_other_pages %}
                <!-- if page have a previous page show the arrow -->
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">&laquo;</a></li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a>
                </li>
                {% endif %}
                
                    
                {% for i in page_obj.paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="?page={{i}}"><span>{{i}}</span></a></li>
                {% endfor %}
                
                <!-- if page have a next page show the arrow -->
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">&raquo;</a></li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&raquo;</a>
                </li>
                {% endif %}
            {% endif %}
        </ul>
    </nav>
</article>
{% endblock body %}

cards/templates/allCards/edit_card.html
{% extends 'base.html' %}
{% block title %}
    <title>Edit Code</title>
{% endblock title %}

{% load bootstrap5 %}

{% block body %}
<article id="rightSide">
    <div class="leftItem">
        <form action="#" method="POST" class="form" enctype='multipart/form-data'>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary w-100" >Edit Code</button>
            {% endbuttons %}
        </form>
        </div>
</article>

{% endblock body %}

cards/templates/allCards/home1.html
{% extends "base.html" %}

{% block body %}
    <article id="rightSide">
        <section id="subject">
            <h1>Search or Add CODE</h1>
        </section>
        <section id="mainLetter">
            <p>This page is about to make your work easy just search what you want 
                in which program language you need 
            </p>
        </section>
        <section id="searchBar">
            <!-- the button will redirect to search page  -->
            <form method="GET" action="{% url 'cardsShow:search' %}">
                <label for="text1" id="labelName">Search Subject Code : </label>
                <input id="text1" type="text" name="search">
                <i class="fas fa-search" id="searchIcon"></i>
                <button type="submit" class="btn btn-primary w-100" >Search</button>
            </form>
        </section>
    </article>

{% endblock body %}

cards/templates/allCards/search_page.html
{% extends 'base.html' %}

{% block title %}
    <title>Search Result </title>
{% endblock title %}

{% block pageImg %}
<!-- do not forget .url for image in django -->
    <link rel="icon" href="{{ Image.url }}">
{% endblock pageImg %}

<!-- {% load bootstrap5 %} -->

{% block body %}
<article id="rightSide">
    <section class="cards">
        
        {% if query %}
            {% for card in result %}
                <article class="card">
                        <div id="imgCard">
                            <img src="{{card.image.url}}" alt="">
                        </div>
                        <div class="codeWriter">
                            {{card.owner}}
                            <!-- {{user.first_name}} -->
                            {{card.publish_at}}
                        </div>
                        <div class="cardSubject">
                            <a href="{% url 'cardsShow:cardDetail' card.slug %}"> {{card.header}} </a>
                        </div>
                        <div class="cardDescription">
                            <p>
                                {{card.description}}
                            </p>
                        </div>
                        
                    </article> 
            {% empty %}
                <h4>There is no results</h4>
                <p>search in another way</p>
            {% endfor %}
        {% else %}
            <h4>dd</h4>
        {% endif %}
            
    </section>
{% endblock body %}

cards/templates/allCards/userCards.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ user.username }}</title>
{% endblock title %}

{% block pageImg %}
<!-- do not forget .url for image in django -->
    <link rel="icon" href="{{ Image.url }}">
{% endblock pageImg %}

<!-- {% load bootstrap5 %} -->

{% block body %}
<article id="rightSide">
    <section class="cards">
        {% for card in page_obj.object_list %}
            <article class="card">
                    <div id="imgCard">
                        <img src="{{card.image.url}}" alt="">
                    </div>
                    <div class="codeWriter">
                        {{card.owner}}
                        {{card.publish_at}}
                    </div>
                    <div class="cardSubject">
                        <a href="{% url 'cardsShow:cardDetail' card.slug %}"> {{card.header}} </a>
                    </div>
                    <div class="cardDescription">
                        <p>
                            {{card.description}}
                        </p>
                    </div>
                    
            </article> 
        {% endfor %}
    </section>
    <!-- paginator setting -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            {% if page_obj.has_other_pages %}
                <!-- if page have a previous page show the arrow -->
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">&laquo;</a></li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a>
                </li>
                {% endif %}
                
                    
                {% for i in page_obj.paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="?page={{i}}"><span>{{i}}</span></a></li>
                {% endfor %}
                
                <!-- if page have a next page show the arrow -->
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">&raquo;</a></li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&raquo;</a>
                </li>
                {% endif %}
            {% endif %}
        </ul>
    </nav>
</article>
{% endblock body %}